### ISSUE TITLE
How to apply the formatter for html.heex files?

### ISSUE THREAD

**Issue by cvkmohan** [feliperenan/heex_formatter#14]
The formatter is working will for the sigil inside ```*.ex``` files. However, it is not working for ```*.html.heex``` files. Should we be adding something to the ```formatter.exs```  file?

**Comment by paulo-silva** [comment]
hey @cvkmohan good point, I've updated our README to tell that inputs from formatter.exs needs to be updated as well, to watch heex files 👍
