### ISSUE TITLE
Formatting introduces unwanted rendered spacing

### ISSUE THREAD

**Issue by megalithic** [feliperenan/heex_formatter#16]
LOVE this project! Thank you to you and the rest of the contribs!

Here's a quick sample of running `heex_formatter` on an almost brand-new Phoenix LiveView project..
 
Code diff of live.html.heex:
https://github.com/megalithic/megalithic.io/pull/2/files#diff-c5cc08848777a65f1977289d91aca51faef0b711e174e6429f083988535a1592

Screenshot of resulting formatting change:
![](https://kaptures.s3.amazonaws.com/tmp/ss_20220121_142522.png)

You can see that the live flash alerts render a space so they show up with their styling (padding/etc)..

Thoughts on how to avoid this? Is there a CSS-specific fix, perhaps?

**Comment by feliperenan** [comment]
Hi @megalithic 👋🏻 

TBH, I'm not sure how to handle this here since in order to format the code, this extra space is necessary. The solution might be not rendering the tag in case it doesn't have content?. Something like:

```eex
  <%= if info_flash = get_flash(@conn, :info) do %>
    <p class="alert alert-info" role="alert">
      <%= info_flash %>
    </p>
  <% end %>
  <%= if error_flash = get_flash(@conn, :error) do %>
    <p class="alert alert-danger" role="alert">
      <%= error_flash %>
    </p>
  <% end %>
```

It would require changing Phoenix generator but I'm 100% sure if that's the way to go 🤔

**Comment by josevalim** [comment]
@feliperenan I think we can also solve it with CSS. There is a configuration to ignore whitespace or something similar.

**Comment by feliperenan** [comment]
I'm linking the PR here so I guess we may close this issue once it gets merged on Phoenix :)

https://github.com/phoenixframework/phoenix/pull/4667

**Comment by haslinger** [comment]
I would like to throw into the discussion, that this issue is not restricted to the question, if tags being displayed at all. Whitespace changes formatting in lots of cases, e.g. table cells, spacing between words, line breaks, ... just to name a few.

A few thoughts:
* A hint to prevent the formatter from breaking up a <tag>text</tag> in several lines?
* The issue in itself is not specific to elixir in any way. So maybe other formatters have solved that already?

**Comment by johanerikssonpingpayments** [comment]
As @haslinger says, this is not restricted to the question. As an example, the Bulma content example ([https://bulma.io/documentation/elements/content/](https://bulma.io/documentation/elements/content/)) has a lot of unwanted whitespace introduced in the browser after formatting.

![image](https://user-images.githubusercontent.com/84183870/152174463-b3dd07f0-13c3-4b87-a46a-876131c14ec8.png)
![image](https://user-images.githubusercontent.com/84183870/152174516-4c0252e5-61e5-484c-91f5-7b191381cc98.png)
![image](https://user-images.githubusercontent.com/84183870/152174655-ae891069-c268-423f-87b4-87e0950fa50b.png)

**Comment by josevalim** [comment]
The original issue has been fixed in main. However new bugs may have surfaced, so please give it a try!

**Comment by dnsbty** [comment]
This fixed some issues I was seeing. Thank you!

**Comment by almirsarajcic** [comment]
I'm seeing the same issue with the latest version ([`cec8daf221004781d8bcb76e5ad38f0ce7a0e991`](https://github.com/feliperenan/heex_formatter/tree/cec8daf221004781d8bcb76e5ad38f0ce7a0e991)).

Do I need to add a condition or should it work automatically?
It converts
```
<div
    class="flex alert alert-danger"
    role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"
  ><%= live_flash(@flash, :error) %></div>
```
into
```
<div
    class="flex alert alert-danger"
    role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"
  >
    <%= live_flash(@flash, :error) %>
  </div>
```
which shows that empty red container like in the screenshot.

**Comment by 03juan** [comment]
@almirsarajcic either wrap it

```html
<%= if live_flash(@flash, :error)  do %>
  <div
    class="flex alert alert-danger"
    role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"
  ><%= live_flash(@flash, :error) %></div>
<% end %>
```

or manually upgrade to the upcoming function component implementation
[`<.flash flash={get_flash(@conn)} kind={:info} />`](https://github.com/phoenixframework/phoenix/pull/4667/files#diff-c131ff1f49713fa46b969255f8d92a3693a0aa24a2dbbfdc0de61e918730fe1fR2)

[`def flash(assigns) do ...`](https://github.com/phoenixframework/phoenix/pull/4667/files#diff-14d5660536a62d8b5ca5d1df183e912d1726991cd2bd2867a5e34147ec9dd6beR22)

**Comment by feliperenan** [comment]
I'm about to archive this project so I'm closing this. This will be fixed soon once we merge that PR in Phoenix, but other cases will need to be handled by either conditionally rendering or css.
