### ISSUE TITLE
Case issue again....

### ISSUE THREAD

**Issue by maxmannen** [feliperenan/heex_formatter#24]
Causes error:

```
def table_row(assigns) do
    ~H"""
    <tr>
      <%= for value <- @values do %>
        <td class="border-2">
          <%= case value.type do %>
          <% :text -> %>
          Do something
          <% _ -> %>
            Do something else
          <% end %>
        </td>
      <% end %>
    </tr>
    """
  end
```

If I remove the Do something (Which makes the code pointless btw) it "works":

```
def table_row(assigns) do
    ~H"""
    <tr>
      <%= for value <- @values do %>
        <td class="border-2">
          <%= case value.type do %>
          <% :text -> %>
          <% _ -> %>
            Do something else
          <% end %>
        </td>
      <% end %>
    </tr>
    """
  end
```
* (ArgumentError) errors were found at the given arguments:

  * 2nd argument: out of range

    (stdlib 3.17) :binary.copy("  ", -1)
    lib/heex_formatter/phases/format.ex:199: HeexFormatter.Phases.Format.indent_expression/2
    lib/heex_formatter/phases/format.ex:140: HeexFormatter.Phases.Format.token_to_string/2
    lib/heex_formatter/phases/format.ex:44: anonymous fn/2 in HeexFormatter.Phases.Format.run/2
    (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/heex_formatter/phases/format.ex:43: HeexFormatter.Phases.Format.run/2
    (elixir 1.13.1) lib/code/formatter.ex:1323: Code.Formatter.maybe_sigil_to_algebra/4
    (elixir 1.13.1) lib/code/formatter.ex:456: Code.Formatter.quoted_to_algebra/3

**Comment by feliperenan** [comment]
Thanks for reporting 💪🏻 

It is supposed to be fixed now. Please, take a look and let me know otherwise  🙌🏻

**Comment by maxmannen** [comment]
Works! Excellent work! Thanks!
