### ISSUE TITLE
Handle HTML comments and script tag with EEx tags

### ISSUE THREAD

**Issue by feliperenan** [feliperenan/heex_formatter#25]
### A bit of Context

`EEx.Tokenizer.tokenize` returns a single token for multiline comments. For instance, given the following input:

```html
<section>
  <!-- commenting out this div
  <div>
    <p class="my-class">text</p>
  </div>
  -->
</section>
```

The `EEx.Tokenizer` will return the following structure:
```elixir
[
  {:text, 0, 0,
   '  <!-- Inline comment -->\n  <section>\n    <!-- commenting out this div\n    <div>\n      <p class="my-class">text</p
>\n    </div>\n    -->\n  </section>\n'},
  {:eof, 8, 1}
]
```

Which is send to `Phoenix.LiveView.Tokenizer` and transformed to:

```elixir
[
  {:tag_open, "section", [], %{column: 3, line: 1}},
  {:text,
   "\n    <!-- commenting out this div\n    <div>\n      <p class=\"my-class\">text</p>\n    </div>\n    -->\n  ",
   %{column_end: 3, line_end: 7}},
  {:tag_close, "section", %{column: 3, line: 7}}
]
```

We get a different structure when there are eex tags included:

Given the HTML with eex tags:

```html
<section>
  <!-- commenting out this div
  <div>
    <p class="my-class"><%= @user.name %></p>
  </div>
  -->
</section>
```

That's the `EEx.Tokenizer` output:

```elixir
[
  {:text, 0, 0,
   '  <section>\n    <!-- commenting out this div\n    <div>\n      <p class="my-class">'},
  {:expr, 3, 27, '=', ' user.name '},
  {:text, 3, 43, '</p>\n    </div>\n    -->\n  </section>\n'},
  {:eof, 7, 1}
]
```

Which makes the `Phoenix.LiveView.Tokenizer` parse only the closing tags after the `eex` expression.

```elixir
[
  {:tag_open, "section", [], %{column: 3, line: 1}},
  {:text, "\n    <!-- commenting out this div\n    <div>\n      <p class=\"my-class\">",
   %{column_end: 27, line_end: 4}},
  {:eex_tag_render, "<%= user.name %>", %{block?: false, column: 27, line: 3}},
  {:tag_close, "p", %{column: 1, line: 1}},
  {:tag_close, "div", %{column: 5, line: 2}},
  {:text, "\n    -->\n  ", %{column_end: 3, line_end: 4}},
  {:tag_close, "section", %{column: 3, line: 4}}
]
```

PS:  We have the same behaviour on script tags.

### Issue

Given the context above, I'm not sure how to handle this. I guess we shouldn't format stuff within HTML comment and script tags at all. But since `EEx.Tokeziner` extracts eex expressions from these tags, we need to find way to put them together as they are so we can just ignore it.

Before going down this road, I'd like to confirm if there is something we could do in the `Tokenizers` or if I'm missing something.

**Comment by feliperenan** [comment]
@josevalim I'd love your thoughts here 🙌🏻

**Comment by josevalim** [comment]
We could definitely change the tokenizer to return more information but I also think you shouldn’t really changed what is inside script and html comments. Scripts in particular mean you can change the meaning of the JS code.

**Comment by feliperenan** [comment]
Yeah, that is what I've thought too. Would it make sense to change the EEx tokenizer to not extract eex expressions from these tags? 

In other words, it should have the same return as when there aren't `eex` expressions. Something like:

```elixir
[
  {:text, 0, 0,
   '  <!-- Inline comment -->\n  <section>\n    <!-- commenting out this div\n    <div>\n      <p class="my-class"><%= @user.name %></p
>\n    </div>\n    -->\n  </section>\n'},
  {:eof, 8, 1}
]
```

**Comment by josevalim** [comment]
We can't do that change, unfortunately. However, if you need to put the parts of the HTML comment together, we can change it to emit `:comment_begin` instead of `:text`. And then `:comment_end`.

**Comment by feliperenan** [comment]
I see. That would help a bit so we don't need to identify comments start/end ourselves from the text. Could we do the same for scripts? 🤔

**Comment by josevalim** [comment]
Yes, we can! Perhaps, to not change the existing HEEx code, we can add this information to the metadata:

    {:text, "\n    <!-- commenting out this div\n    <div>\n      <p class=\"my-class\">",
     %{column_end: 27, line_end: 4, context: :comment_start}},

If there is no context, we can skip the field altogether.

**Comment by feliperenan** [comment]
There is one edge case though. Imagine we have another opening tag right after the iex expression. Something like:

```html
        <!-- commenting out this div
        <div>
          <p><%= @user.name %></p>
          <p 
              class="my-class">
                text
          </p>
        </div>
        -->
```

Because we have everything after the eex expression tokenized, we don't know how to concatenate it back just looking at the HTMLTokenizer:

```elixir
[
  {:tag_open, "section", [], %{column: 1, line: 1}},
  # comment begin
  {:text, "\n  <!-- commenting out this div\n  <div>\n    <p>",
   %{column_end: 8, line_end: 4}},
  {:eex_tag_render, "<%= @user.name %>", %{block?: false, column: 8, line: 3}},
  # Here are the tokens which are still inside the comment but after the eex expression 
  {:tag_close, "p", %{column: 1, line: 1}},
  {:text, "\n    ", %{column_end: 5, line_end: 2}},
  {:tag_open, "p", [{"class", {:string, "my-class", %{delimiter: 34}}}],
   %{column: 5, line: 2}},
  {:text, "\n      text\n    ", %{column_end: 5, line_end: 5}},
  {:tag_close, "p", %{column: 5, line: 5}},
  {:text, "\n  ", %{column_end: 3, line_end: 6}},
  {:tag_close, "div", %{column: 3, line: 6}},
  {:text, "\n  -->\n", %{column_end: 1, line_end: 8}},
  # comment end
  {:tag_close, "section", %{column: 1, line: 8}},
  {:text, "\n", %{column_end: 1, line_end: 9}}
]
```

**Comment by josevalim** [comment]
@feliperenan that should work. I believe the reason it does not work is because the html tokenizer state is being discarded here: https://github.com/feliperenan/heex_formatter/blob/main/lib/heex_formatter/phases/tokenizer.ex#L41 :)

**Comment by josevalim** [comment]
You should do something like this instead:

https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/html_engine.ex#L120-L122

And also remember to call `finalize` if you don't call it yet! https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/html_engine.ex#L48
