### ISSUE TITLE
Skipping formatter plugin HeexFormatter because module cannot be found

### ISSUE THREAD

**Issue by cvkmohan** [feliperenan/heex_formatter#3]
1. I added the module to deps.
2. mix deps.get
3. Added the line ```plugins: [HeexFormatter]``` to ```.formatter.exs```
I am getting an error message that plugins: ```Skipping formatter plugin HeexFormatter because module cannot be found```
My application is on ```elixir 1.13.2``` and ```phoenix 1.6.6```

**Comment by cvkmohan** [comment]
You need to run ```mix compile``` also before running ```mix format```.

```elixir
          <%= live_patch to: @return_to,
                class: "absolute top-6 right-6 text-gray-400 flex space-x-1 items-center",
                aria_label: "close modal",
                id: "close-modal-button" do %>
            <span class="text-sm">(esc)</span>
            <.remix_icon icon="close-line" class="text-2xl" />
          <% end %>
```
the above piece of code is giving the error. The error message is ```expected attribute name```

**Comment by feliperenan** [comment]
Hi @krushi123  👋🏻 

Yes. You need to run `mix compile` after adding it as a dependency.  Also, this project is not yet able to process `eex` clauses. We are on it right now 🙌🏻

**Comment by feliperenan** [comment]
@krushi123 Eex tags are supposed to be formatted now. There are still some cases to be covered but feel free to give it a try and report any other issue you have 🙌🏻

**Comment by cvkmohan** [comment]
Thanks @feliperenan and @paulo-silva  for all the effort. It is working well for the eex tags.
One case that I have observed is - if there is a html attribute with no value, the formatter is failing. For example ```autofocus``` attribute is not a key-value pair. That scenario is breaking the formatter.

**Comment by cvkmohan** [comment]
A small addon question. If I am using vscode as the editor and elixirLS extension - formatOnSave is working for a regular elixir code. It is not working the same for heex formatting. How to enable that?

**Comment by feliperenan** [comment]
@cvkmohan thanks for reporting this. Feel free to open issues for such cases so we will fix them as we go.

It is supposed to work on save as it does for `mix format`. I'm not VScode user myself, so I can't provide much help here. Maybe @paulo-silva has some idea? 🙌🏻

**Comment by paulo-silva** [comment]
Sure guys, I can take a look on it 👍

**Comment by feliperenan** [comment]
@cvkmohan BTW, this commit https://github.com/feliperenan/heex_formatter/commit/098f3a80e30ab94e4bb64c7ab0fa66d25ea09809 fixes the issue with attributes without values.

**Comment by cvkmohan** [comment]
I confirm that it is working. I will continue using it, and open issues if I find any. Thanks for the prompt responses.

**Comment by cvkmohan** [comment]
> Sure guys, I can take a look on it 👍
It looks like the elixir-ls module does not use ```mix format``` as in this discussion https://github.com/elixir-lsp/vscode-elixir-ls/discussions/224 
A fresh issue has been created here https://github.com/elixir-lsp/elixir-ls/issues/660

**Comment by paulo-silva** [comment]
yeah, I was about to link it here 😅, thanks @cvkmohan for all your help opening issues so far, so probably soon we will be able to auto-format in vscode 😄

**Comment by nicocirio** [comment]
> Hi @krushi123 👋🏻
> 
> Yes. You need to run `mix compile` after adding it as a dependency. Also, this project is not yet able to process `eex` clauses. We are on it right now 🙌🏻

Great job! this formatter is really great! :rocket: 

Have been trying to solve `Skipping formatter plugin HeexFormatter because module cannot be found` error, and `mix compile` fixed the issue. Perhaps this step could be added to `README.md`?

**Comment by feliperenan** [comment]
It was there but we removed by accident I guess. Let's add it back.
