### ISSUE TITLE
Output is very broken when `br` is used as a void element

### ISSUE THREAD

**Issue by atavistock** [feliperenan/heex_formatter#31]
The valid HTML of `<br>` which is handled fine by heex appears to break this formatter.  I have not tried other valid void elements but I expect they might behave the same way.  For reference: https://dev.w3.org/html5/html-author/#void

**Comment by paulo-silva** [comment]
Hi @atavistock, thanks for reporting this 🙇‍♂️ 

Would you mind putting an example here, please? It can be a simple one, like input, output, expected output.

**Comment by atavistock** [comment]
Oh, on looking at this closer, its not actually broken, just poorly formatted.  I had other issues breaking the page but this one just does this...

Before:
```
<div class="font-bold text-lg leading-snug">
  Effortless<br>
  And<br>
  Easy.
</div>
```

After:
```
<div class="font-bold text-lg leading-snug">
  Effortless
  <br>And
    <br>Easy.
    </div>
```

**Comment by paulo-silva** [comment]
Hey @atavistock this should be fixed now 🙌
