### ISSUE TITLE
Suddenly module became unusable.

### ISSUE THREAD

**Issue by cvkmohan** [feliperenan/heex_formatter#38]
Hello @feliperenan and @paulo-silva. Thanks for actively improving the module to fix all the issues encountered. However, the package in its current form, can not be added to a new project. Mainly, because you have changed the live_view dependency to your fork.  May be you could have made a release without that fork ( even if it meant some feature is not working) - that would have allowed a smooth usage of the package.  
It is not a complaint - just a suggestion. Thanks again.

**Comment by cvkmohan** [comment]
Created a pull request. So, closing this issue.

**Comment by feliperenan** [comment]
Thanks 💙
