### ISSUE TITLE
Adds newline above doctype declaration

### ISSUE THREAD

**Issue by moomerman** [feliperenan/heex_formatter#41]
Thanks so much for building this formatter, it is great.  I spotted a couple of things in my codebase after running the formatter (using latest a208ca8ba3138ed448dc192552526b2904ab9382)

Given the following input:

```
<!DOCTYPE html>
```

the output contains a newline above the doctype declaration

```

<!DOCTYPE html>
```

Thanks!

**Comment by feliperenan** [comment]
@moomerman it is supposed to be fixed given my last commit. Let me know otherwise 🙌🏻

**Comment by moomerman** [comment]
⚡ @feliperenan yep that fixes it for me - thanks!
