### ISSUE TITLE
HTML comments produce unexpected nesting

### ISSUE THREAD

**Issue by moomerman** [feliperenan/heex_formatter#42]
Given this input

```html
<!-- this is a HTML comment -->
<div>
  <p>Hello</p>
</div>
```

the formatter outputs

```html
<!-- this is a HTML comment --><div>
  <p>Hello</p>
</div>
```

I wouldn't have expected it to change

**Comment by moomerman** [comment]
Another example with more nesting:

input:

```html
<div>
  <!-- A comment -->
  <p>
    <!-- I like comments -->
    Hello
  </p>
</div>
```

output: 

```html
<div><!-- A comment -->  <p><!-- I like comments -->
    Hello
  </p>
</div>
```

**Comment by feliperenan** [comment]
Hi @moomerman 

Thanks for reporting this. I'm working in a refactor that will change how the formatter works and hopefully this will also solve this issue.

**Comment by feliperenan** [comment]
This issue is supposed to be fixed in master. Please, do let me know otherwise 🙌🏻 .
