### ISSUE TITLE
Sponsorship of project

### ISSUE THREAD

**Issue by jsmestad** [feliperenan/heex_formatter#43]
If you are open to it, I think you should allow sponsors to this Github repo. I for one would gladly sponsor some of the development.

**Comment by feliperenan** [comment]
Hi @jsmestad 👋🏻 

I'm glad you are offering this but our plan is to introduce this formatter directly to Live View once we get enough feedback here.

I'd encourage you to run `mix hex.sponsors` in case you are not aware of and sponsor any other project that brings your attention. I'm pretty sure there will be something cool to sponsor 💪🏻 

Thank you ❤️
