### ISSUE TITLE
Unable to run mix deps.get

### ISSUE THREAD

**Issue by CallumVass** [feliperenan/heex_formatter#51]
Hi,

I followed the instructions on the README.md file in a new phoenix project, however, I receive the following error:
```
mix deps.get
Dependencies have diverged:
* phoenix_live_view (Hex package)
  the dependency phoenix_live_view in mix.exs is overriding a child dependency:

  > In mix.exs:
    {:phoenix_live_view, "~> 0.17.5", [env: :prod, repo: "hexpm", hex: "phoenix_live_view"]}

  > In deps/heex_formatter/mix.exs:
    {:phoenix_live_view, [env: :prod, git: "https://github.com/phoenixframework/phoenix_live_view.git"]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

Adding `override: true` to `phoenix_live_view` fixes the error, however, I then encounter an issue when I run `mix format`:
```
mix format
Skipping formatter plugin HeexFormatter because module cannot be found
```

Am I doing something wrong? This is with the latest version of Phoenix.

**Comment by feliperenan** [comment]
Hi @CallumVass 

At the moment, this library depends on live view master. Because of that, you need override LiveView in your mix.exs:

```elixir
 {:phoenix_live_view, "~> 0.17.6", override: true},
```

Also, make sure you are using Elixir 1.13.

Thanks and let me know if that works for you 🙌🏻
