### ISSUE TITLE
Stripping parentheses from anonymous function

### ISSUE THREAD

**Issue by sbaildon** [feliperenan/heex_formatter#53]
I have an anonymous function call where the parentheses are stripped. See the line immediately following  `~H"""`

I had this

```elixir
  def link(%{to: _, inner_block: _} = assigns) do
    assigns =
      assigns
      |> assign_new(:action, fn -> &live_patch/2 end)

    ~H"""
    <%= @action.(to: @to) do %>
      <span class="text-blue-600">
        <%= render_slot(@inner_block) %>
      </span>
    <% end %>
    """
  end
```

become this

```elixir
  def link(%{to: _, inner_block: _} = assigns) do
    assigns =
      assigns
      |> assign_new(:action, fn -> &live_patch/2 end)

    ~H"""
    <%= @action. to: @to do %>
      <span class="text-blue-600">
        <%= render_slot(@inner_block) %>
      </span>
    <% end %>
    """
  end
```

The compiler was not happy about that!

**Comment by feliperenan** [comment]
Hi @sbaildon

Thank you for reporting this. Right now I'm working in a refactor (I'm almost there) and I'll make sure this will be covered there.

**Comment by feliperenan** [comment]
Hi 👋🏻 

Please, could you try the new version in master and see if still face this?

**Comment by 03juan** [comment]
Can confirm master no longer strips the parenthesis 👍

**Comment by feliperenan** [comment]
Great :) I will close this then
