### ISSUE TITLE
mix formats removes intentional single blanks

### ISSUE THREAD

**Issue by haslinger** [feliperenan/heex_formatter#59]
Running `mix format` removes some spaces, that should stay in place in heex templates:
```diff
-    Last <%= length(@backlog_feeds) %> of <%= @feedcount %> backlog feeds
+    Last<%= length(@backlog_feeds) %>of<%= @feedcount %>backlog feeds
```
In case you want to see more context, the file, I ran mix format on is [over here](https://github.com/PanoptikumIO/pan/blob/main/lib/pan_web/templates/feed_backlog/index.html.heex#L24).
Happy to provide more information, basically all versions used are [current](https://github.com/PanoptikumIO/pan/blob/main/mix.lock).

Cheers, and happy to see this project making progress! The last changes fixed lots of issues I had with the formatter! :heart_eyes:

**Comment by feliperenan** [comment]
Ohh.. I'll have a look. Thanks for reporting 🙏🏻

**Comment by haslinger** [comment]
Ran the formatter again and I believe it's now working perfectly for all of my templates. Will test more thoroughly the next days.
I want to say thank you, cause it awesome, that we get a common standard for our templates as well. Actually I was not expecting it to fix all the issues I saw in earlier releases so quickly. I am truly impressed! 🙇🏻
