### ISSUE TITLE
additional new lines above and below HTML comment tags every time formatter is run

### ISSUE THREAD

**Issue by 03juan** [feliperenan/heex_formatter#60]
This code grows in new lines above and below the comment when it contains an eex block

Before:
```html
<div></div>
<!-- <%= "comment" %> -->
<div></div>
```

After running formatter twice:
```html
<div></div>


<!-- <%= "comment" %> -->


<div></div>
```

**Comment by 03juan** [comment]
@feliperenan I appreciate your work! ❤️

**Comment by feliperenan** [comment]
Thank you 🙌🏻 

Hopefully this is now fixed given my last commit 🙏🏻
