### ISSUE TITLE
Whitespace lost when removing newlines

### ISSUE THREAD

**Issue by kerryb** [feliperenan/heex_formatter#65]
This is similar to #59, but still seems to be an issue in the latest main (c1ffe57).

When text is separated from an element by a newline, and the formatter closes them up, it doesn’t insert whitespace, which will change the appearance of the HTML.

For example, formatting this:

```html
<button>
  <i class="fa-solid fa-xmark"></i>
  Close
</button>
```

gives this:

```html
<button>
  <i class="fa-solid fa-xmark"></i>Close
</button>
```

when it should probably give this:

```html
<button>
  <i class="fa-solid fa-xmark"></i> Close
</button>
```

This only happens when there was a newline – if the text and element are on the same line, separated by a space, then the space is correctly preserved.

Awesome work, by the way – great to see the benefits of the formatter extended to heex!

**Comment by josevalim** [comment]
Ah, this is probably because we only check if the text starts with space, but we should probably check for any of `\r\n\t\s`!
