### ISSUE TITLE
Formatting remove spaces between `Text <tag>` to `Text<tag>`

### ISSUE THREAD

**Issue by lubien** [feliperenan/heex_formatter#68]
Just wanted to report a small issue that might be related to https://github.com/feliperenan/heex_formatter/issues/65

I have this formatted code (removed a few things for clarity):

```heex
          <p>
            You can also<a href>sign up</a>or<a href>sign in</a>
            with your email address.
          </p>
```

Which appears with words together as `You can alsosign uporsign in with your email address.`

Any attempt to separate the parts will format to the code above

**Comment by 03juan** [comment]
It does seem to remove the leading and trailing whitespace inside the anchor element, but the external whitespace is not affected.

Moving the spaces outside of the anchor works as expected in commit #5fdff54

```html
    <p>
      You can also <a href>sign up</a> or <a href>sign in</a> with your email address.
    </p>
```

renders to `You can also sign up or sign in with your email address.`

The browser will ignore the double whitespace in `also <a href> sign up </a> or <a href> sign in </a> with` (note the whitespace before each of the opening/closing tags). So it would be safe to leave the extra spaces alone as part of the html text intended by the user?

**Comment by josevalim** [comment]
Correct. Latest version should preserve white space between text and tags. We could preserve the space immediately inside tags but is that really desired? The less we do, the less we normalize.

**Comment by 03juan** [comment]
That makes sense. After writing the above I had a look at the [css white space spec](https://drafts.csswg.org/css-text/#white-space-phase-1) and in example 7 they write:

> Note that there will be two [spaces](https://drafts.csswg.org/css-text/#spaces) between A and B, and none between B and C. This is best avoided by putting spaces outside the element instead of just inside the opening and closing tags and, where practical, by relying on implicit bidirectionality instead of explicit embedding levels.

So they agree that it's not desired to preserve it inside the tag.

**Comment by feliperenan** [comment]
As far as I get, there is nothing to do in here, right? I'm closing it for now, let me know otherwise 🙌🏻
