### ISSUE TITLE
Negative indentation error after assigning a var inside an HTML tag

### ISSUE THREAD

**Issue by agenestar** [feliperenan/heex_formatter#72]
I have found an error in the formatter when creating new variables inside an HTML tag. It indents the variable creation with 0 tabs, when it should be 1. And when it gets to the next HEEX tag tries to indent it with -1 and it breaks. 

This is a an example that breaks: 
```
<p>
  <% a = 1 %> <%# indents it to 0, should be 1 tab %>
</p>
<%= "hello" %> <%# indents it to -1, ERROR %>
```

This is the error:
```
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: out of range

    (stdlib 3.15.2) :binary.copy("  ", -1)
    lib/heex_formatter/formatter.ex:504: HeexFormatter.Formatter.format_eex/2
    lib/heex_formatter/formatter.ex:199: HeexFormatter.Formatter.token_to_string/2
    lib/heex_formatter/formatter.ex:63: anonymous fn/2 in HeexFormatter.Formatter.format/2
    (elixir 1.13.0) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/heex_formatter/formatter.ex:61: HeexFormatter.Formatter.format/2
    (mix 1.13.0) lib/mix/tasks/format.ex:560: Mix.Tasks.Format.format_file/2
    (elixir 1.13.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
```

I have not been able to find the error in the `formatter.ex` code. But I can create some tests for this.

**Comment by feliperenan** [comment]
Thanks for reporting.

It seems you are not using the latest version. Please, make sure you are using the last commit from main and let me know if you face any issues.

Thanks

**Comment by agenestar** [comment]
You are right, I didnt have the last version in my local. With the last version it is working as expected. 

Thanks for your contribution!
