### ISSUE TITLE
Elixir code inside elixir expression tag with do block is not formatted

### ISSUE THREAD

**Issue by mulias** [feliperenan/heex_formatter#75]
Currently using 4f53f70

Formatting this
```
<%= live_redirect(
       to: "/my/path",
  class: "my class"
) do %>
  My Link
<% end %>

      <%= label class: "control-label"   do %>
  <%=    radio_button(:user, :choice,
 "Choice") %>
<% end %>

<%= for foo   <- @foos    do %>
  <%= foo %>
<% end     %>
```

Produces this
```
<%= live_redirect(
       to: "/my/path",
  class: "my class"
) do %>
  My Link
<% end %>

<%= label class: "control-label"   do %>
  <%= radio_button(:user, :choice, "Choice") %>
<% end %>

<%= for foo   <- @foos    do %>
  <%= foo %>
<% end %>

```

The elixir code inside of `<%= ... do %>` lines is not getting formatted

**Comment by feliperenan** [comment]
Yeah, we don't format eex blocks :(. That is a bit hard to do so we decided to not go for it. Also because Heex templates supports components. In the future, most of this code will be written as Phoenix components which is formatted correctly.

Thanks for bringing this up though.
