### ISSUE TITLE
Error on format

### ISSUE THREAD

**Issue by maxmannen** [feliperenan/heex_formatter#9]
Great job with this!
Get this error though:
mix format failed for file: lib/classrooms_web/components/ui/submission.ex
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: out of range

    (stdlib 3.17) :binary.copy("  ", -1)
    lib/heex_formatter/phases/format.ex:138: HeexFormatter.Phases.Format.indent_expression/1
    lib/heex_formatter/phases/format.ex:131: HeexFormatter.Phases.Format.token_to_string/2
    lib/heex_formatter/phases/format.ex:37: anonymous fn/2 in HeexFormatter.Phases.Format.run/2
    (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/heex_formatter/phases/format.ex:36: HeexFormatter.Phases.Format.run/2
    (elixir 1.13.1) lib/code/formatter.ex:1323: Code.Formatter.maybe_sigil_to_algebra/4
    (elixir 1.13.1) lib/code/formatter.ex:456: Code.Formatter.quoted_to_algebra/3

defmodule Ui.Submission do
  use Phoenix.Component
  import Phoenix.HTML.Link

  def state(assigns) do
    css = "#{show?(assigns.chosen_course)}"

    ~H"""
     <span x-data="{ tooltip: false }"
       x-on:mouseover="tooltip = true"
       x-on:mouseleave="tooltip = false"
       class="ml-2 h-5 w-5 cursor-pointer">
       <div class="text-sm text-white absolute bg-gray-700 rounded-lg p-2
        transform -translate-y-8 translate-x-8" x-show="tooltip">
        Klicka för att se elevens arbete
       </div>
     <%= case @state do %>
     <% "NEW" -> %>
     <%=link target: "_blank", to: @url do %>
     <button class={css}>
     <Box.icons
     type="regular"
     name="file-find"
     size="20"
     class="stroke-red-900 fill-red-900"
     />
     </button>
     <% end %>
     <% "CREATED" -> %>
     <%=link target: "_blank", to: @url do %>
     <button class={css} >
     <Box.icons
     type="regular"
     name="edit"
     size="20"
     class="stroke-yellow-600 fill-yellow-600"
     />
     </button>
     <% end %>
     <% "TURNED_IN" -> %>
     <%=link target: "_blank", to: @url do %>
     <button class={css}>
     <Box.icons
     type="regular"
     name="task"
     size="20"
     class="stroke-green-600 fill-green-600"
     />
     </button>
     <% end %>
     <% "RECLAIMED_BY_STUDENT" -> %>
     <%=link target: "_blank", to: @url do %>
     <button class={css}>
     <Box.icons
     type="regular"
     name="arrow-from-right"
     size="20"
     class="stroke-gray-600 fill-gray-600"
     />
     </button>
     <% end %>
     <% "RETURNED" -> %>
     <%=link target: "_blank", to: @url do %>
      <button class={css}>
      <Box.icons
     type="regular"
     name="recycle"
     size="20"
     class="stroke-gray-600 fill-gray-600"
     />
     </button>
     <% end %>
     <% end %>
     </span>
    """
  end

  defp show?(true) do
    "drop-shadow-md hover:drop-shadow-xl "
  end

  defp show?(nil) do
    "drop-shadow-md hover:drop-shadow-xl"
  end

  defp show?(_) do
    "drop-shadow-md hover:drop-shadow-xl opacity-25"
  end
end

**Comment by feliperenan** [comment]
Hi @maxmannen 👋🏻 . 

Thank you for reporting this.

Would you mind sending a better example? this one is hard for me to reproduce since your template contains some modules and functions that are not present in the example.  I'd love if you could create a public repo so I could run so I could run the format there myself 🤚🏻

**Comment by maxmannen** [comment]
Ok, I scaled it down until the error disappeared

same error:
defmodule Ui.SubmissionTest do
  use Phoenix.Component

  def state(assigns) do
    ~H"""
     <div>
     <%= case @state do %>
     <% "NEW" -> %>
     <button>
     button
     </button>
     <% end %>
     </div>
    """
  end
end

Remove the "CASE" and it disappears

Help?

**Comment by maxmannen** [comment]
its @state in the example above.

**Comment by maxmannen** [comment]
its @state with small letters of course. This editor changes it.

**Comment by feliperenan** [comment]
@maxmannen please, take a look again and let me know if you are facing this issue 🙌🏻

**Comment by maxmannen** [comment]
Works like a charm!
Thank you!
